name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/peanut-butler:latest

    - name: Deploy Docker container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/peanut-butler:latest
        docker stop peanut-butler || true
        docker rm peanut-butler || true
        docker run -d --name peanut-butler \
          -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
          -e DISCORD_USER_ID=${{ secrets.DISCORD_USER_ID }} \
          -e LANGUAGE=${{ secrets.LANGUAGE }} \
          -e USERNAME=${{ secrets.USERNAME }} \
          -e HOST=${{ secrets.HOST }} \
          -e PORT=${{ secrets.PORT }} \
          -v ${{ secrets.DATA_PATH }}:/usr/src/app/data \
          ${{ secrets.DOCKER_USERNAME }}/peanut-butler:latest
