name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up WireGuard
      uses: egor-tensin/setup-wireguard@v1
      with:
        endpoint: '${{ secrets.WG_SERVER_IP }}:51820'
        endpoint_public_key: '${{ secrets.WG_SERVER_PUBLIC_KEY }}'
        ips: '10.0.0.2/24'
        allowed_ips: '0.0.0.0/0'
        private_key: '${{ secrets.WG_CLIENT_PRIVATE_KEY }}'
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/peanut-butler:latest
    
    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/peanut-butler:latest
          docker stop peanut-butler || true
          docker rm peanut-butler || true
          docker run -d --name peanut-butler ${{ secrets.DOCKER_USERNAME }}/peanut-butler:latest
